export {
  formatNames,
  formatDate,
  applyTextCase,
  titleCase,
  sentenceCase,
  capitalize,
  stripNocaseSpans,
  ordinal,
  longOrdinal,
  roman,
  pageRange,
  escapeHtml,
  stripFormatting,
  toHtml,
  NameFormatConfig,
  DateFormatConfig,
} from '@citestyle/types'
